version: '3'
services:
 db-postgres:
   image: postgres:11.1-alpine
   restart: always
   environment:
     - POSTGRES_DB=flask-deploy
     - POSTGRES_USER=db_user
     - POSTGRES_PASSWORD=db_password
   ports:
     - 5432:5432

 migration:
   build: .
   restart: on-failure
   environment:
     - APP_ENV=${APP_ENV}
   command: /bin/bash -c "sleep 15; flask db upgrade"
   depends_on:
     - db-postgres

 app:
   build: .
   ports:
    - "80:8000"
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - db-postgres
     - migration
