"""empty message

Revision ID: 19ef11718322
Revises: 
Create Date: 2019-05-29 18:39:29.633504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ef11718322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork_pointer',
    sa.Column('artpiece_id', sa.String(length=36), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=600), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=450), nullable=True),
    sa.Column('page_url', sa.String(length=300), nullable=True),
    sa.Column('meta_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('artpiece_id')
    )
    op.create_index(op.f('ix_artwork_pointer_artist'), 'artwork_pointer', ['artist'], unique=False)
    op.create_index(op.f('ix_artwork_pointer_artpiece_id'), 'artwork_pointer', ['artpiece_id'], unique=True)
    op.create_index(op.f('ix_artwork_pointer_created_at'), 'artwork_pointer', ['created_at'], unique=False)
    op.create_index(op.f('ix_artwork_pointer_image_url'), 'artwork_pointer', ['image_url'], unique=True)
    op.create_index(op.f('ix_artwork_pointer_meta_url'), 'artwork_pointer', ['meta_url'], unique=True)
    op.create_index(op.f('ix_artwork_pointer_name'), 'artwork_pointer', ['name'], unique=False)
    op.create_index(op.f('ix_artwork_pointer_page_url'), 'artwork_pointer', ['page_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artwork_pointer_page_url'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_name'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_meta_url'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_image_url'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_created_at'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_artpiece_id'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_artist'), table_name='artwork_pointer')
    op.drop_table('artwork_pointer')
    # ### end Alembic commands ###
