"""artwork_pointer

Revision ID: 22d8c096d9a6
Revises: 
Create Date: 2019-04-11 23:09:06.365419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d8c096d9a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork_pointer',
    sa.Column('artpiece_id', sa.String(length=36), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=450), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('artpiece_id')
    )
    op.create_index(op.f('ix_artwork_pointer_artpiece_id'), 'artwork_pointer', ['artpiece_id'], unique=True)
    op.create_index(op.f('ix_artwork_pointer_created_at'), 'artwork_pointer', ['created_at'], unique=False)
    op.create_index(op.f('ix_artwork_pointer_url'), 'artwork_pointer', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artwork_pointer_url'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_created_at'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_artpiece_id'), table_name='artwork_pointer')
    op.drop_table('artwork_pointer')
    # ### end Alembic commands ###
