"""links table

Revision ID: 246c4b1f9bcc
Revises: 
Create Date: 2018-08-03 15:48:08.610548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246c4b1f9bcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_original_url'), 'link', ['original_url'], unique=True)
    op.create_index(op.f('ix_link_target_url'), 'link', ['target_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_target_url'), table_name='link')
    op.drop_index(op.f('ix_link_original_url'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
