"""empty message

Revision ID: 58a1b5a9bb25
Revises: a1c1fd72efda
Create Date: 2019-07-11 08:32:49.070429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a1b5a9bb25'
down_revision = 'a1c1fd72efda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artpiece_youtube_url', table_name='artpiece')
    op.create_index(op.f('ix_artpiece_youtube_url'), 'artpiece', ['youtube_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artpiece_youtube_url'), table_name='artpiece')
    op.create_index('ix_artpiece_youtube_url', 'artpiece', ['youtube_url'], unique=1)
    # ### end Alembic commands ###
