"""artwork_pointer

Revision ID: 99e266a5d223
Revises: 22d8c096d9a6
Create Date: 2019-04-12 09:41:46.140520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e266a5d223'
down_revision = '22d8c096d9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork_pointer', sa.Column('name', sa.String(length=600), nullable=True))
    op.add_column('artwork_pointer', sa.Column('page_url', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_artwork_pointer_name'), 'artwork_pointer', ['name'], unique=True)
    op.create_index(op.f('ix_artwork_pointer_page_url'), 'artwork_pointer', ['page_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artwork_pointer_page_url'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_name'), table_name='artwork_pointer')
    op.drop_column('artwork_pointer', 'page_url')
    op.drop_column('artwork_pointer', 'name')
    # ### end Alembic commands ###
