"""empty message

Revision ID: a1c1fd72efda
Revises: 
Create Date: 2019-07-11 07:56:01.294371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c1fd72efda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artpiece',
    sa.Column('artpiece_id', sa.String(length=36), nullable=False),
    sa.Column('artpiece_name', sa.String(length=100), nullable=True),
    sa.Column('artwork_type', sa.String(length=100), nullable=True),
    sa.Column('artpiece_explanation', sa.Text(), nullable=True),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.Column('artist_bio', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=450), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=450), nullable=True),
    sa.Column('youtube_url', sa.String(length=450), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('last_sold_for', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('is_for_sale', sa.Boolean(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('remaining_printings', sa.Integer(), nullable=True),
    sa.Column('includes_physical', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('artpiece_id')
    )
    op.create_index(op.f('ix_artpiece_artist'), 'artpiece', ['artist'], unique=False)
    op.create_index(op.f('ix_artpiece_artpiece_id'), 'artpiece', ['artpiece_id'], unique=True)
    op.create_index(op.f('ix_artpiece_artpiece_name'), 'artpiece', ['artpiece_name'], unique=False)
    op.create_index(op.f('ix_artpiece_artwork_type'), 'artpiece', ['artwork_type'], unique=False)
    op.create_index(op.f('ix_artpiece_created_at'), 'artpiece', ['created_at'], unique=False)
    op.create_index(op.f('ix_artpiece_date_created'), 'artpiece', ['date_created'], unique=False)
    op.create_index(op.f('ix_artpiece_grade'), 'artpiece', ['grade'], unique=False)
    op.create_index(op.f('ix_artpiece_image_url'), 'artpiece', ['image_url'], unique=True)
    op.create_index(op.f('ix_artpiece_thumbnail_url'), 'artpiece', ['thumbnail_url'], unique=True)
    op.create_index(op.f('ix_artpiece_website'), 'artpiece', ['website'], unique=False)
    op.create_index(op.f('ix_artpiece_youtube_url'), 'artpiece', ['youtube_url'], unique=True)
    op.create_table('artwork_pointer',
    sa.Column('artpiece_id', sa.String(length=36), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=600), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=450), nullable=True),
    sa.Column('page_url', sa.String(length=300), nullable=True),
    sa.Column('meta_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('artpiece_id')
    )
    op.create_index(op.f('ix_artwork_pointer_artist'), 'artwork_pointer', ['artist'], unique=False)
    op.create_index(op.f('ix_artwork_pointer_artpiece_id'), 'artwork_pointer', ['artpiece_id'], unique=True)
    op.create_index(op.f('ix_artwork_pointer_created_at'), 'artwork_pointer', ['created_at'], unique=False)
    op.create_index(op.f('ix_artwork_pointer_image_url'), 'artwork_pointer', ['image_url'], unique=True)
    op.create_index(op.f('ix_artwork_pointer_meta_url'), 'artwork_pointer', ['meta_url'], unique=True)
    op.create_index(op.f('ix_artwork_pointer_name'), 'artwork_pointer', ['name'], unique=False)
    op.create_index(op.f('ix_artwork_pointer_page_url'), 'artwork_pointer', ['page_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artwork_pointer_page_url'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_name'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_meta_url'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_image_url'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_created_at'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_artpiece_id'), table_name='artwork_pointer')
    op.drop_index(op.f('ix_artwork_pointer_artist'), table_name='artwork_pointer')
    op.drop_table('artwork_pointer')
    op.drop_index(op.f('ix_artpiece_youtube_url'), table_name='artpiece')
    op.drop_index(op.f('ix_artpiece_website'), table_name='artpiece')
    op.drop_index(op.f('ix_artpiece_thumbnail_url'), table_name='artpiece')
    op.drop_index(op.f('ix_artpiece_image_url'), table_name='artpiece')
    op.drop_index(op.f('ix_artpiece_grade'), table_name='artpiece')
    op.drop_index(op.f('ix_artpiece_date_created'), table_name='artpiece')
    op.drop_index(op.f('ix_artpiece_created_at'), table_name='artpiece')
    op.drop_index(op.f('ix_artpiece_artwork_type'), table_name='artpiece')
    op.drop_index(op.f('ix_artpiece_artpiece_name'), table_name='artpiece')
    op.drop_index(op.f('ix_artpiece_artpiece_id'), table_name='artpiece')
    op.drop_index(op.f('ix_artpiece_artist'), table_name='artpiece')
    op.drop_table('artpiece')
    # ### end Alembic commands ###
